import type { Metadata } from "next";
import { CareerApplicationForm } from "@/components/career-application-form";
import { PageHero } from "@/components/page-hero";
import { JsonLd } from "@/lib/jsonld";
import { site } from "@/lib/site";

export const metadata: Metadata = { title: "Careers & Job Opportunities", description: "Apply for construction, manufactured-home, CDL driver, carpenter, equipment operator, laborer, and diesel technician careers with Home Placer in the Myrtle Beach area.", alternates: { canonical: "/careers" } };
const openings = [
  ["Site Work & Equipment Operator", "$20–$28 per hour, depending on experience", "Help prepare home sites and operate the equipment that keeps our land-and-home projects moving."],
  ["Laborer", "$16–$21 per hour, depending on experience", "Support deliveries, setup, site work, repairs, and the hands-on work behind every completed home."],
  ["CDL Driver", "Pay based on experience", "Move equipment and materials safely between our jobs, yards, and manufacturing partners."],
  ["Carpenter", "Pay based on experience", "Use finish-work and repair skills on manufactured-home setup, service, and customer care."],
  ["Diesel / Heavy Equipment Service Technician", "Pay based on experience", "Maintain and repair the trucks and heavy equipment our crews rely on every day."],
] as const;
export default function CareersPage() { const jobs = openings.map(([title, pay, description]) => ({ "@type": "JobPosting", title, description: `${description} ${pay}. Apply online with Home Placer.`, datePosted: "2026-08-30", employmentType: "FULL_TIME", hiringOrganization: { "@type": "Organization", name: site.legalName, sameAs: site.url }, jobLocation: { "@type": "Place", address: { "@type": "PostalAddress", addressLocality: "Myrtle Beach", addressRegion: "SC", addressCountry: "US" } }, directApply: true })); return <><JsonLd data={{ "@context": "https://schema.org", "@graph": jobs }} /><PageHero eyebrow="Careers at Home Placer" title="Build the groundwork. Build a career.">We build manufactured homes on land across the Grand Strand. Join a crew that takes pride in doing the work right.</PageHero><section className="container-x py-16"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{openings.map(([title, pay, description]) => <article key={title} className="rounded-card border border-stone-line bg-stone-surface p-6"><p className="text-sm font-semibold text-brand-700">{pay}</p><h2 className="mt-2 font-display text-2xl font-semibold text-stone-ink">{title}</h2><p className="mt-3 text-sm leading-relaxed text-stone-muted">{description}</p><a href="#apply" className="mt-5 inline-flex text-sm font-semibold text-brand-700 hover:text-brand-900">Apply for this role →</a></article>)}</div></section><section id="apply" className="border-y border-stone-line bg-stone-surface py-16"><div className="container-x grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-wider text-brand-600">Apply online</p><h2 className="mt-2 font-display text-3xl font-semibold text-stone-ink">Tell us what you can do.</h2><p className="mt-4 text-stone-muted">Choose a position, share your experience, and add a resume or references if you have them. We also welcome general applications from skilled people in the manufactured-home and construction trades.</p></div><div className="rounded-card border border-stone-line bg-stone-bg p-6 sm:p-8"><CareerApplicationForm /></div></div></section></>; }
