import { asset } from "./asset";
import manifest from "../../data/gallery-manifest.json";

export interface GalleryItem {
  src: string;
  category: "homes" | "development";
  alt: string;
}

// The curated photos in public/gallery, listed in data/gallery-manifest.json
// (regenerated by scripts/build-manifests.mjs at build — no runtime fs on the
// Cloudflare Workers runtime). home-* = manufactured homes we've placed
// (finished or mid-setup); dev-* = land development / communities.
export function getGallery(): GalleryItem[] {
  const files = (manifest as string[]).slice().sort();
  return files.map((f) => {
    const isHome = f.startsWith("home-");
    return {
      src: asset(`/gallery/${f}`),
      category: isHome ? "homes" : "development",
      alt: isHome
        ? "New manufactured home placed on land by Home Placer in Horry County, SC"
        : "Home Placer land development and manufactured-home community on the Grand Strand, SC",
    };
  });
}

export function galleryByCategory(cat: "homes" | "development") {
  return getGallery().filter((g) => g.category === cat);
}
