import { asset } from "./asset";
import manifest from "../../data/gallery-manifest.json";

export interface GalleryItem {
  src: string;
  category: "homes" | "development";
  alt: string;
  width: number;
  height: number;
}

// Keep intrinsic dimensions with the manifest so the masonry grid reserves the
// correct space before each real photograph loads. These originals are curated
// gallery assets (not CMS uploads), so their dimensions are stable at build time.
const galleryDimensions: Record<string, [number, number]> = {
  "dev-01.jpg": [1600, 903],
  "dev-02.jpg": [1600, 897],
  "dev-03.jpg": [1600, 903],
  "dev-04.jpg": [1600, 903],
  "dev-05.jpg": [1600, 903],
  "dev-06.jpg": [1600, 903],
  "dev-07.jpg": [1600, 903],
  "home-01.jpg": [1600, 1200],
  "home-02.jpg": [1600, 1200],
  "home-03.jpg": [1600, 903],
  "home-04.jpg": [1600, 1200],
  "home-05.jpg": [1600, 1200],
  "home-06.jpg": [1200, 1600],
  "home-07.jpg": [1600, 1200],
  "home-08.jpg": [1600, 903],
  "home-09.jpg": [1600, 903],
  "home-10.jpg": [1600, 903],
};

// The curated photos in public/gallery, listed in data/gallery-manifest.json
// (regenerated by scripts/build-manifests.mjs at build — no runtime fs on the
// Cloudflare Workers runtime). home-* = manufactured homes we've placed
// (finished or mid-setup); dev-* = land development / communities.
export function getGallery(): GalleryItem[] {
  const files = (manifest as string[]).slice().sort();
  return files.map((f) => {
    const isHome = f.startsWith("home-");
    const [width, height] = galleryDimensions[f] ?? [1600, 1200];
    return {
      src: asset(`/gallery/${f}`),
      category: isHome ? "homes" : "development",
      width,
      height,
      alt: isHome
        ? "New manufactured home placed on land by Home Placer in Horry County, SC"
        : "Home Placer land development and manufactured-home community on the Grand Strand, SC",
    };
  });
}

export function galleryByCategory(cat: "homes" | "development") {
  return getGallery().filter((g) => g.category === cat);
}
