import data from "../../data/placed-homes.json";

// A real home Home Placer placed and sold (the /recently-placed showcase).
// Generated by scripts/gen-placed-homes.py — joins sold-homes + placements
// (model) + galleries (photos) + the Paragon re-export (acres, heated sqft).
export type PlacedHome = {
  slug: string;
  mls: string;
  address: string;
  town: string;
  townSlug: string;
  beds: number;
  baths: number;
  style: string;
  withLand: boolean;
  price: number;
  lat: number | null;
  lon: number | null;
  photo: string;
  photos: string[];
  modelName: string | null;
  modelSlug: string | null;
  lotAcres: number | null;
  sqftHeated: number | null;
  closeDate: string | null; // ISO YYYY-MM-DD (Paragon closing date)
};

export type PlacedTown = { name: string; slug: string; homes: PlacedHome[] };

export function getAllPlacedHomes(): PlacedHome[] {
  return data as PlacedHome[];
}

export function getPlacedHome(slug: string): PlacedHome | undefined {
  return getAllPlacedHomes().find((h) => h.slug === slug);
}

const TOWN_ORDER = ["Conway", "Loris", "Aynor", "Longs", "Myrtle Beach"];

export function placedHomesByTown(): PlacedTown[] {
  const map = new Map<string, PlacedTown>();
  for (const h of getAllPlacedHomes()) {
    if (!map.has(h.town)) map.set(h.town, { name: h.town, slug: h.townSlug, homes: [] });
    map.get(h.town)!.homes.push(h);
  }
  return [...map.values()].sort((a, b) => {
    const ia = TOWN_ORDER.indexOf(a.name);
    const ib = TOWN_ORDER.indexOf(b.name);
    return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib);
  });
}

// Homes in the same town (for "more placed homes nearby"), excluding one slug.
export function relatedPlacedHomes(slug: string, town: string, n = 3): PlacedHome[] {
  return getAllPlacedHomes()
    .filter((h) => h.town === town && h.slug !== slug)
    .slice(0, n);
}
